---
version: "3"

vars:
  testArgs: -v

tasks:
  unit:
    desc: "Run unit tests"
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -cover -coverprofile=rate.cov -tags unit .

  integration:
    desc: "Run integration tests"
    aliases: [ int, e2e ]
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -cover -coverprofile=rate.cov -tags integration .

  bench:
    desc: "Run benchmarks"
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -cover -coverprofile=rate.cov -tags integration -bench=. -benchtime=5s -benchmem .

  fmt:
    internal: true
    desc: "Invoke fmt"
    cmds:
      - goimports -w .
      - go fmt ./...

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func=rate.cov

  uncover:
    desc: "Show uncovered source"
    deps: [ install:uncover ]
    cmds:
      - uncover rate.cov

  install:uncover:
    desc: "Install uncover"
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
