# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json:
  spec:
    - '#/id'
    - '#/$schema'
    - '#/patternProperties'
    - '#/definitions'
    - '#/definitions/Info/patternProperties'
    - '#/definitions/Contact/patternProperties'
    - '#/definitions/License/patternProperties'
    - '#/definitions/ExternalDocumentation/patternProperties'
    - '#/definitions/Server/patternProperties'
    - '#/definitions/ServerVariable/patternProperties'
    - '#/definitions/Tag/patternProperties'
    - '#/definitions/Paths/patternProperties'
    - '#/definitions/Components/patternProperties'
    - '#/definitions/Components/properties/schemas/patternProperties'
    - '#/definitions/Components/properties/responses/patternProperties'
    - '#/definitions/Components/properties/parameters/patternProperties'
    - '#/definitions/Components/properties/examples/patternProperties'
    - '#/definitions/Components/properties/requestBodies/patternProperties'
    - '#/definitions/Components/properties/headers/patternProperties'
    - '#/definitions/Components/properties/securitySchemes/patternProperties'
    - '#/definitions/Components/properties/links/patternProperties'
    - '#/definitions/Components/properties/callbacks/patternProperties'
