name: 'Git Dirty Check'
description: >-
  Check whether any Git-worthy changes have been made to the checkout.
runs:
  using: "composite"
  steps:
    - name: "Dirty git Check"
      shell: bash
      run: |
        git add .
        if [[ -n "$(git status --porcelain)" ]]; then
           PAGER= git diff --cached
           exit 1
        fi
