---
version: "3"

vars:
  tag: v0.0.0
<<<<<<< HEAD
  base: tykio/golang-cross:1.21-bookworm
=======
  image: internal/plugin-compiler
>>>>>>> 6f3540e34... [TT-11855] remove unnecessary packages resolving cve reports (#6223)
  sha:
    sh: git rev-parse HEAD
  root:
    sh: git rev-parse --show-toplevel

tasks:
  build:
<<<<<<< HEAD
    desc: "Build plugin compiler"
    dir: '{{.root}}'
    cmds:
      - docker build --no-cache --progress=plain --build-arg GO_VERSION=1.21 --build-arg BASE_IMAGE={{.base}} --build-arg GITHUB_TAG={{.tag}} --build-arg GITHUB_SHA={{.sha}} --platform=linux/amd64 --rm -t internal/plugin-compiler -f ci/images/plugin-compiler/Dockerfile .
=======
    desc: "Build test docker image"
    dir: '{{.root}}'
    cmds:
      - docker build --no-cache --progress=plain --build-arg GITHUB_TAG={{.tag}} --build-arg GITHUB_SHA={{.sha}} --platform=linux/amd64 --rm -t {{.image}} -f ci/images/plugin-compiler/Dockerfile .

  test:
    desc: "Run test docker image"
    dir: '{{.root}}'
    cmds:
      - docker run -it --rm --platform=linux/amd64 --entrypoint=/bin/bash {{.image}}

>>>>>>> 6f3540e34... [TT-11855] remove unnecessary packages resolving cve reports (#6223)
