---
name: Build CI Base Image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - docker/ci-base/**
      - go.mod
      - go.sum
      - .taskfiles/install/Taskfile.yml

jobs:
  base-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: Checkout Tyk
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v2

      - name: CI base image
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: false
          context: .
          file: docker/ci-base/latest/Dockerfile
          platforms: linux/amd64
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_TAG=${{ github.ref }}
            BASE_IMAGE=golang:1.19
          tags: |
            tykio/tyk-base-ci:5.1
            tykio/tyk-base-ci:latest

      - name: CI base image (5 LTS)
        uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          file: docker/ci-base/latest/Dockerfile
          platforms: linux/amd64
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_TAG=${{ github.ref }}
            BASE_IMAGE=golang:1.16
          tags: |
            tykio/tyk-base-ci:5.0
